# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 16
    target-branch: "dev"
    commit-message:
      prefix: "[api]"
    groups:
      kotest:
        patterns:
          - "io.kotest*"
      netty:
        patterns:
          - "io.netty*"
      retrofit:
        patterns:
          - "com.squareup.retrofit2*"
      okhttp:
        patterns:
          - "com.squareup.okhttp3*"
      rx:
        patterns:
          - "io.reactivex.rxjava3*"
      jackson:
        patterns:
          - "com.fasterxml.jackson*"

  - package-ecosystem: "npm"
    directory: "/desktop"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 64
    target-branch: "dev"
    commit-message:
      prefix: "[desktop]"
    groups:
      angular:
        patterns:
          - "@angular*"
      types:
        patterns:
          - "@types*"

  - package-ecosystem: "npm"
    directory: "/desktop/app"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    commit-message:
      prefix: "[desktop]"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    commit-message:
      prefix: "[github-actions]"
