# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 64
    target-branch: "dev"
    commit-message:
      prefix: "[api]"
    groups:
      kotest:
        patterns:
          - "io.kotest*"
      netty:
        patterns:
          - "io.netty*"
      squareup:
        patterns:
          - "com.squareup*"
      rx:
        patterns:
          - "io.reactivex*"
      fasterxml:
        patterns:
          - "com.fasterxml*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      exposed:
        patterns:
          - "org.jetbrains.exposed*"
      apache:
        patterns:
          - "org.apache*"
      ktor:
        patterns:
          - "io.ktor*"
      junit:
        patterns:
          - "org.junit*"

  - package-ecosystem: "npm"
    directory: "/desktop"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 64
    target-branch: "dev"
    commit-message:
      prefix: "[desktop]"
    groups:
      angular:
        patterns:
          - "@angular*"
      types:
        patterns:
          - "@types*"

  - package-ecosystem: "npm"
    directory: "/desktop/app"
    schedule:
      interval: "daily"
    target-branch: "dev"
    commit-message:
      prefix: "[desktop]"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    commit-message:
      prefix: "[docs]"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    commit-message:
      prefix: "[github-actions]"
