package nebulosa.skycatalog

enum class SkyObjectType(val description: String) {
    UNKNOWN("Unknown"),
    GALAXY("Galaxy"),
    ACTIVE_GALAXY("Active Galaxy"),
    RADIO_GALAXY("Radio Galaxy"),
    INTERACTING_GALAXY("Interacting Galaxy"),
    QUASAR("Quasar"),
    STAR_CLUSTER("Star Cluster"),
    OPEN_STAR_CLUSTER("Open Star Cluster"),
    GLOBULAR_STAR_CLUSTER("Globular Star Cluster"),
    STELLAR_ASSOCIATION("Stellar Association"),
    STAR_CLOUD("Star Cloud"),
    NEBULA("Nebula"),
    PLANETARY_NEBULA("Planetary Nebula"),
    DARK_NEBULA("Dark Nebula"),
    REFLECTION_NEBULA("Reflection Nebula"),
    BIPOLAR_NEBULA("Bipolar Nebula"),
    EMISSION_NEBULA("Emission Nebula"),
    CLUSTER_ASSOCIATED_WITH_NEBULOSITY("Cluster Associated With Nebulosity"),
    HII_REGION("HII Region"),
    SUPERNOVA_REMNANT("Supernova Remnant"),
    INTERSTELLAR_MATTER("Interstellar Matter"),
    EMISSION_OBJECT("Emission Object"),
    BL_LACERTAE_OBJECT("BL Lacertae Object"),
    BLAZAR("Blazar"),
    MOLECULAR_CLOUD("Molecular Cloud"),
    YOUNG_STELLAR_OBJECT("Young Stellar Object"),
    POSSIBLE_QUASAR("Possible Quasar"),
    POSSIBLE_PLANETARY_NEBULA("Possible Planetary Nebula"),
    PROTOPLANETARY_NEBULA("Protoplanetary Nebula"),
    STAR("Star"),
    SYMBIOTIC_STAR("Symbiotic Star"),
    EMISSION_LINE_STAR("Emission Line Star"),
    SUPERNOVA_CANDIDATE("Supernova Candidate"),
    SUPER_NOVA_REMNANT_CANDIDATE("Supernova Remnant Candidate"),
    CLUSTER_OF_GALAXIES("Cluster of Galaxies"),
    PART_OF_GALAXY("Part of Galaxy"),
    REGION_OF_THE_SKY("Region of the Sky"),
}
