package nebulosa.skycatalog

enum class SkyObjectType(
    val description: String,
    private vararg val codes: String,
) {
    ACTIVE_GALAXY_NUCLEUS("Active Galaxy Nucleus", "AGN", "AG?"),
    ALPHA2_CVN_VARIABLE("alpha2 CVn Variable", "a2*", "a2?"),
    ASSOCIATION_OF_STARS("Association of Stars", "As*", "As?"),
    ASYMPTOTIC_GIANT_BRANCH_STAR("Asymptotic Giant Branch Star", "AB*", "AB?"),
    BETA_CEP_VARIABLE("beta Cep Variable", "bC*", "bC?"),
    BE_STAR("Be Star", "Be*", "Be?"),
    BLACK_HOLE("Black Hole", "BH", "BH?"),
    BLAZAR("Blazar", "Bla", "Bz?"),
    BLUE_COMPACT_GALAXY("Blue Compact Galaxy", "bCG"),
    BLUE_OBJECT("Blue Object", "blu"),
    BLUE_STRAGGLER("Blue Straggler", "BS*", "BS?"),
    BLUE_SUPERGIANT("Blue Supergiant", "s*b", "s?b"),
    BL_LAC("BL Lac", "BLL", "BL?"),
    BRIGHTEST_GALAXY_IN_A_CLUSTER_BCG("Brightest Galaxy in a Cluster (BCG)", "BiC"),
    BROWN_DWARF("Brown Dwarf", "BD*", "BD?"),
    BUBBLE("Bubble", "bub"),
    BY_DRA_VARIABLE("BY Dra Variable", "BY*", "BY?"),
    CARBON_STAR("Carbon Star", "C*", "C*?"),
    CATACLYSMIC_BINARY("Cataclysmic Binary", "CV*", "CV?"),
    CENTIMETRIC_RADIO_SOURCE("Centimetric Radio Source", "cm"),
    CEPHEID_VARIABLE("Cepheid Variable", "Ce*", "Ce?"),
    CHEMICALLY_PECULIAR_STAR("Chemically Peculiar Star", "Pe*", "Pe?"),
    CLASSICAL_CEPHEID_VARIABLE("Classical Cepheid Variable", "cC*"),
    CLASSICAL_NOVA("Classical Nova", "No*", "No?"),
    CLOUD("Cloud", "Cld"),
    CLUSTER_OF_GALAXIES("Cluster of Galaxies", "ClG", "C?G"),
    CLUSTER_OF_STARS("Cluster of Stars", "Cl*", "Cl?", "C?*"),
    COMETARY_GLOBULE_PILLAR("Cometary Globule / Pillar", "CGb"),
    COMPACT_GROUP_OF_GALAXIES("Compact Group of Galaxies", "CGG"),
    COMPOSITE_OBJECT_BLEND("Composite Object, Blend", "mul"),
    DARK_CLOUD_NEBULA("Dark Cloud (nebula)", "DNe"),
    DELTA_SCT_VARIABLE("delta Sct Variable", "dS*"),
    DENSE_CORE("Dense Core", "cor"),
    DOUBLE_OR_MULTIPLE_STAR("Double or Multiple Star", "**", "**?"),
    ECLIPSING_BINARY("Eclipsing Binary", "EB*", "EB?"),
    ELLIPSOIDAL_VARIABLE("Ellipsoidal Variable", "El*", "El?"),
    EMISSION_LINE_GALAXY("Emission-line galaxy", "EmG"),
    EMISSION_LINE_STAR("Emission-line Star", "Em*"),
    EMISSION_OBJECT("Emission Object", "EmO"),
    ERUPTIVE_VARIABLE("Eruptive Variable", "Er*", "Er?"),
    EVOLVED_STAR("Evolved Star", "Ev*", "Ev?"),
    EVOLVED_SUPERGIANT("Evolved Supergiant", "sg*", "sg?"),
    EXTRA_SOLAR_PLANET("Extra-solar Planet", "Pl", "Pl?"),
    FAR_IR_SOURCE_30_M("Far-IR source (λ >= 30 µm)", "FIR"),
    GALAXY("Galaxy", "G", "G?"),
    GALAXY_IN_PAIR_OF_GALAXIES("Galaxy in Pair of Galaxies", "GiP"),
    GALAXY_TOWARDS_A_CLUSTER_OF_GALAXIES("Galaxy towards a Cluster of Galaxies", "GiC"),
    GALAXY_TOWARDS_A_GROUP_OF_GALAXIES("Galaxy towards a Group of Galaxies", "GiG"),
    GAMMA_DOR_VARIABLE("gamma Dor Variable", "gD*"),
    GAMMA_RAY_BURST("Gamma-ray Burst", "gB"),
    GAMMA_RAY_SOURCE("Gamma-ray Source", "gam"),
    GLOBULAR_CLUSTER("Globular Cluster", "GlC", "Gl?"),
    GLOBULE_LOW_MASS_DARK_CLOUD("Globule (low-mass dark cloud)", "glb"),
    GRAVITATIONALLY_LENSED_IMAGE("Gravitationally Lensed Image", "LeI", "LI?"),
    GRAVITATIONALLY_LENSED_IMAGE_OF_A_GALAXY("Gravitationally Lensed Image of a Galaxy", "LeG"),
    GRAVITATIONALLY_LENSED_IMAGE_OF_A_QUASAR("Gravitationally Lensed Image of a Quasar", "LeQ"),
    GRAVITATIONAL_LENS("Gravitational Lens", "gLe", "Le?"),
    GRAVITATIONAL_LENS_SYSTEM_LENS_IMAGES("Gravitational Lens System (lens+images)", "gLS", "LS?"),
    GRAVITATIONAL_SOURCE("Gravitational Source", "grv"),
    GRAVITATIONAL_WAVE_EVENT("Gravitational Wave Event", "GWE"),
    GROUP_OF_GALAXIES("Group of Galaxies", "GrG", "Gr?"),
    HERBIG_AE_BE_STAR("Herbig Ae/Be Star", "Ae*", "Ae?"),
    HERBIG_HARO_OBJECT("Herbig-Haro Object", "HH"),
    HIGH_MASS_X_RAY_BINARY("High Mass X-ray Binary", "HXB", "HX?"),
    HIGH_PROPER_MOTION_STAR("High Proper Motion Star", "PM*"),
    HIGH_VELOCITY_CLOUD("High-velocity Cloud", "HVC"),
    HIGH_VELOCITY_STAR("High Velocity Star", "HV*"),
    HII_GALAXY("HII Galaxy", "H2G"),
    HII_REGION("HII Region", "HII"),
    HI_21CM_SOURCE("HI (21cm) Source", "HI"),
    HORIZONTAL_BRANCH_STAR("Horizontal Branch Star", "HB*", "HB?"),
    HOT_SUBDWARF("Hot Subdwarf", "HS*", "HS?"),
    INFRA_RED_SOURCE("Infra-Red Source", "IR"),
    INTERACTING_GALAXIES("Interacting Galaxies", "IG"),
    INTERSTELLAR_FILAMENT("Interstellar Filament", "flt"),
    INTERSTELLAR_MEDIUM_OBJECT("Interstellar Medium Object", "ISM"),
    INTERSTELLAR_SHELL("Interstellar Shell", "sh"),
    IRREGULAR_VARIABLE("Irregular Variable", "Ir*"),
    LINER_TYPE_ACTIVE_GALAXY_NUCLEUS("LINER-type Active Galaxy Nucleus", "LIN"),
    LONG_PERIOD_VARIABLE("Long-Period Variable", "LP*", "LP?"),
    LOW_MASS_STAR("Low-mass Star", "LM*", "LM?"),
    LOW_MASS_X_RAY_BINARY("Low Mass X-ray Binary", "LXB", "LX?"),
    LOW_SURFACE_BRIGHTNESS_GALAXY("Low Surface Brightness Galaxy", "LSB"),
    MAIN_SEQUENCE_STAR("Main Sequence Star", "MS*", "MS?"),
    MASER("Maser", "Mas"),
    MASSIVE_STAR("Massive Star", "Ma*", "Ma?"),
    METRIC_RADIO_SOURCE("Metric Radio Source", "mR"),
    MICRO_LENSING_EVENT("(Micro)Lensing Event", "Lev"),
    MID_IR_SOURCE_3_TO_30_M("Mid-IR Source (3 to 30 µm)", "MIR"),
    MILLIMETRIC_RADIO_SOURCE("Millimetric Radio Source", "mm"),
    MIRA_VARIABLE("Mira Variable", "Mi*", "Mi?"),
    MOLECULAR_CLOUD("Molecular Cloud", "MoC"),
    MOVING_GROUP("Moving Group", "MGr"),
    NEAR_IR_SOURCE_3_M("Near-IR Source (λ < 3 µm)", "NIR"),
    NEBULA("Nebula", "GNe"),
    NEUTRON_STAR("Neutron Star", "N*", "N*?"),
    NOT_AN_OBJECT_ERROR_ARTEFACT("Not an Object (Error, Artefact, ...)", "err"),
    OBJECT_OF_UNKNOWN_NATURE("Object of Unknown Nature", "?"),
    OH_IR_STAR("OH/IR Star", "OH*", "OH?"),
    OPEN_CLUSTER("Open Cluster", "OpC"),
    OPTICAL_SOURCE("Optical Source", "Opt"),
    ORION_VARIABLE("Orion Variable", "Or*"),
    OUTFLOW("Outflow", "out", "of?"),
    PAIR_OF_GALAXIES("Pair of Galaxies", "PaG"),
    PART_OF_A_GALAXY("Part of a Galaxy", "PoG"),
    PART_OF_CLOUD("Part of Cloud", "PoC"),
    PLANETARY_NEBULA("Planetary Nebula", "PN", "PN?"),
    POST_AGB_STAR("Post-AGB Star", "pA*", "pA?"),
    PROTO_CLUSTER_OF_GALAXIES("Proto Cluster of Galaxies", "PCG"),
    PULSAR("Pulsar", "Psr"),
    PULSATING_VARIABLE("Pulsating Variable", "Pu*", "Pu?"),
    QUASAR("Quasar", "QSO", "Q?"),
    RADIO_BURST("Radio Burst", "rB"),
    RADIO_GALAXY("Radio Galaxy", "rG"),
    RADIO_SOURCE("Radio Source", "Rad"),
    RED_GIANT_BRANCH_STAR("Red Giant Branch star", "RG*", "RB?"),
    RED_SUPERGIANT("Red Supergiant", "s*r", "s?r"),
    REFLECTION_NEBULA("Reflection Nebula", "RNe"),
    REGION_DEFINED_IN_THE_SKY("Region defined in the Sky", "reg"),
    ROTATING_VARIABLE("Rotating Variable", "Ro*", "Ro?"),
    RR_LYRAE_VARIABLE("RR Lyrae Variable", "RR*", "RR?"),
    RS_CVN_VARIABLE("RS CVn Variable", "RS*", "RS?"),
    RV_TAURI_VARIABLE("RV Tauri Variable", "RV*", "RV?"),
    R_CRB_VARIABLE("R CrB Variable", "RC*", "RC?"),
    SEYFERT_1_GALAXY("Seyfert 1 Galaxy", "Sy1"),
    SEYFERT_2_GALAXY("Seyfert 2 Galaxy", "Sy2"),
    SEYFERT_GALAXY("Seyfert Galaxy", "SyG"),
    SPECTROSCOPIC_BINARY("Spectroscopic Binary", "SB*", "SB?"),
    STAR("Star", "*"),
    STARBURST_GALAXY("Starburst Galaxy", "SBG"),
    STAR_FORMING_REGION("Star Forming Region", "SFR"),
    STELLAR_STREAM("Stellar Stream", "St*"),
    SUB_MILLIMETRIC_SOURCE("Sub-Millimetric Source", "smm"),
    SUPERCLUSTER_OF_GALAXIES("Supercluster of Galaxies", "SCG", "SC?"),
    SUPERNOVA("SuperNova", "SN*", "SN?"),
    SUPERNOVA_REMNANT("SuperNova Remnant", "SNR", "SR?"),
    SX_PHE_VARIABLE("SX Phe Variable", "SX*"),
    SYMBIOTIC_STAR("Symbiotic Star", "Sy*", "Sy?"),
    S_STAR("S Star", "S*", "S*?"),
    TRANSIENT_EVENT("Transient Event", "ev"),
    TYPE_II_CEPHEID_VARIABLE("Type II Cepheid Variable", "WV*", "WV?"),
    T_TAURI_STAR("T Tauri Star", "TT*", "TT?"),
    ULTRA_LUMINOUS_X_RAY_SOURCE("Ultra-luminous X-ray Source", "ULX", "UX?"),
    UNDERDENSE_REGION_OF_THE_UNIVERSE("Underdense Region of the Universe", "vid"),
    UV_EMISSION_SOURCE("UV-emission Source", "UV"),
    VARIABLE_STAR("Variable Star", "V*", "V*?"),
    WHITE_DWARF("White Dwarf", "WD*", "WD?"),
    WOLF_RAYET("Wolf-Rayet", "WR*", "WR?"),
    X_RAY_BINARY("X-ray Binary", "XB*", "XB?"),
    X_RAY_SOURCE("X-ray Source", "X"),
    YELLOW_SUPERGIANT("Yellow Supergiant", "s*y", "s?y"),
    YOUNG_STELLAR_OBJECT("Young Stellar Object", "Y*O", "Y*?");

    companion object {

        @JvmStatic private val ENTRIES = values()
        @JvmStatic private val MAPPED_ENTRIES = HashMap<String, SkyObjectType>(ENTRIES.size * 2)
            .apply { ENTRIES.forEach { entry -> entry.codes.forEach { this[it] = entry } } }

        @JvmStatic
        fun of(type: String) = MAPPED_ENTRIES[type]
    }
}
