package nebulosa.desktop.model

import org.jetbrains.exposed.sql.Table

object DeepSkyObjects : Table("dsos") {
    val id = integer("id")
    val m = integer("m")
    val ngc = integer("ngc")
    val ic = integer("ic")
    val c = integer("c")
    val b = integer("b")
    val sh2 = integer("sh2")
    val vdb = integer("vdb")
    val rcw = integer("rcw")
    val ldn = integer("ldn")
    val lbn = integer("lbn")
    val cr = integer("cr")
    val mel = integer("mel")
    val pgc = integer("pgc")
    val ugc = integer("ugc")
    val arp = integer("arp")
    val vv = integer("vv")
    val dwb = integer("dwb")
    val tr = integer("tr")
    val st = integer("st")
    val ru = integer("ru")
    val vdbha = integer("vdbha")
    val ced = text("ced")
    val pk = text("pk")
    val png = text("png")
    val snrg = text("snrg")
    val aco = text("aco")
    val hcg = text("hcg")
    val eso = text("eso")
    val vdbh = text("vdbh")
    val mB = double("mB")
    val mV = double("mV")
    val rightAscension = double("rightAscension")
    val declination = double("declination")
    val type = text("type")
    val mType = text("mType")
    val majorAxis = double("majorAxis")
    val minorAxis = double("minorAxis")
    val orientation = double("orientation")
    val redshift = double("redshift")
    val parallax = double("parallax")
    val radialVelocity = double("radialVelocity")
    val distance = double("distance")
    val pmRA = double("pmRA")
    val pmDEC = double("pmDEC")
    val constellation = text("constellation")

    override val primaryKey = PrimaryKey(id, name = "pk_dsos_id")
}
