package nebulosa.xisf

import nebulosa.fits.FitsHeaderKey
import nebulosa.fits.FitsKeyword

data object AstronomicalImageProperties : Map<String, FitsHeaderKey?> by mapOf(
    "Observer:EmailAddress" to null,
    "Observer:Name" to null,
    "Observer:PostalAddress" to null,
    "Observer:Website" to null,
    "Organization:EmailAddress" to null,
    "Organization:Name" to null,
    "Organization:PostalAddress" to null,
    "Organization:Website" to null,
    "Observation:CelestialReferenceSystem" to FitsKeyword.RADESYS,
    "Observation:BibliographicReferences" to null,
    "Observation:Center:Dec" to FitsKeyword.DEC,
    "Observation:Center:RA" to FitsKeyword.RA,
    "Observation:Center:X" to null,
    "Observation:Center:Y" to null,
    "Observation:Description" to null,
    "Observation:Equinox" to FitsKeyword.EQUINOX,
    "Observation:GeodeticReferenceSystem" to null,
    "Observation:Location:Elevation" to null,
    "Observation:Location:Latitude" to FitsKeyword.SITELAT,
    "Observation:Location:Longitude" to FitsKeyword.SITELONG,
    "Observation:Location:Name" to null,
    "Observation:RelatedResources" to null,
    "Observation:Time:End" to FitsKeyword.DATE_END,
    "Observation:Time:Start" to null,
    "Observation:Title" to null,
    "Instrument:Camera:Gain" to FitsKeyword.GAIN,
    "Instrument:Camera:ISOSpeed" to FitsKeyword.ISOSPEED,
    "Instrument:Camera:Name" to FitsKeyword.CAMERA,
    "Instrument:Camera:ReadoutNoise" to FitsKeyword.RDNOISE,
    "Instrument:Camera:Rotation" to FitsKeyword.ROTATANG,
    "Instrument:Camera:XBinning" to FitsKeyword.XBINNING,
    "Instrument:Camera:YBinning" to FitsKeyword.YBINNING,
    "Instrument:ExposureTime" to FitsKeyword.EXPOSURE,
    "Instrument:Filter:Name" to FitsKeyword.FILTER,
    "Instrument:Focuser:Position" to FitsKeyword.FILPOS,
    "Instrument:Sensor:TargetTemperature" to null,
    "Instrument:Sensor:Temperature" to null,
    "Instrument:Sensor:XPixelSize" to FitsKeyword.XPIXSZ,
    "Instrument:Sensor:YPixelSize" to FitsKeyword.YPIXSZ,
    "Instrument:Telescope:Aperture" to FitsKeyword.APERDIA,
    "Instrument:Telescope:CollectingArea" to null,
    "Instrument:Telescope:FocalLength" to FitsKeyword.FOCALLEN,
    "Instrument:Telescope:Name" to FitsKeyword.INSTRUME,
    "Image:FrameNumber" to null,
    "Image:GroupId" to null,
    "Image:SubgroupId" to null,
    "Processing:Description" to null,
    // "Processing:History" to null, // Too long.
)
