-- NOTE: Why UpperCase? https://www.h2database.com/html/grammar.html?highlight=DATABASE_TO_UPPER&search=DATABASE_TO_UPPER#firstFound

CREATE TABLE IF NOT EXISTS CALIBRATION_FRAMES(
    ID IDENTITY NOT NULL PRIMARY KEY,
    TYPE TINYINT NOT NULL DEFAULT 0,
    "GROUP" VARCHAR(512) NOT NULL,
    FILTER VARCHAR(256),
    EXPOSURE_TIME BIGINT NOT NULL DEFAULT 0,
    TEMPERATURE DOUBLE PRECISION NOT NULL DEFAULT 0,
    WIDTH INTEGER DEFAULT 0,
    HEIGHT INTEGER DEFAULT 0,
    BIN_X TINYINT DEFAULT 0,
    BIN_Y TINYINT DEFAULT 0,
    GAIN DOUBLE PRECISION NOT NULL DEFAULT 0,
    PATH VARCHAR(4096) NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE
);
