package nebulosa.query.simbad

enum class SimbadObjectType(
    val description: String,
    val code: String,
) {
    SEYFERT_GALAXY("Seyfert Galaxy", "SyG"),
    BROWN_DWARF("Brown Dwarf", "BD*"),
    MOLECULAR_CLOUD("Molecular Cloud", "MoC"),
    TRANSIENT_EVENT("Transient Event", "ev"),
    CEPHEID_VARIABLE("Cepheid Variable", "Ce*"),
    COMPACT_GROUP_OF_GALAXIES("Compact Group of Galaxies", "CGG"),
    COMPOSITE_OBJECT_BLEND("Composite Object, Blend", "mul"),
    RV_TAURI_VARIABLE("RV Tauri Variable", "RV*"),
    CLOUD("Cloud", "Cld"),
    CATACLYSMIC_BINARY("Cataclysmic Binary", "CV*"),
    PLANETARY_NEBULA("Planetary Nebula", "PN"),
    ERUPTIVE_VARIABLE("Eruptive Variable", "Er*"),
    WOLF_RAYET("Wolf-Rayet", "WR*"),
    RR_LYRAE_VARIABLE_CANDIDATE("RR Lyrae Variable Candidate", "RR?"),
    CATACLYSMIC_BINARY_CANDIDATE("Cataclysmic Binary Candidate", "CV?"),
    GRAVITATIONAL_LENS_SYSTEM_LENS_IMAGES("Gravitational Lens System (lens+images)", "gLS"),
    BLAZAR("Blazar", "Bla"),
    SYMBIOTIC_STAR_CANDIDATE("Symbiotic Star Candidate", "Sy?"),
    BUBBLE("Bubble", "bub"),
    GALAXY_TOWARDS_A_GROUP_OF_GALAXIES("Galaxy towards a Group of Galaxies", "GiG"),
    X_RAY_BINARY("X-ray Binary", "XB*"),
    BLUE_COMPACT_GALAXY("Blue Compact Galaxy", "bCG"),
    GRAVITATIONAL_LENS_SYSTEM_LENS_IMAGES_CANDIDATE("Gravitational Lens System (lens+images) Candidate", "LS?"),
    S_STAR_CANDIDATE("S Star Candidate", "S*?"),
    QUASAR_CANDIDATE("Quasar Candidate", "Q?"),
    MID_IR_SOURCE_3_TO_30_M("Mid-IR Source (3 to 30 µm)", "MIR"),
    BY_DRA_VARIABLE_CANDIDATE("BY Dra Variable Candidate", "BY?"),
    NEUTRON_STAR("Neutron Star", "N*"),
    RV_TAURI_VARIABLE_CANDIDATE("RV Tauri Variable Candidate", "RV?"),
    GLOBULE_LOW_MASS_DARK_CLOUD("Globule (low-mass dark cloud)", "glb"),
    ACTIVE_GALAXY_NUCLEUS("Active Galaxy Nucleus", "AGN"),
    CLUSTER_OF_STARS("Cluster of Stars", "Cl*"),
    RED_GIANT_BRANCH_STAR_CANDIDATE("Red Giant Branch star Candidate", "RB?"),
    GRAVITATIONAL_LENS_CANDIDATE("Gravitational Lens Candidate", "Le?"),
    STELLAR_STREAM("Stellar Stream", "St*"),
    TYPE_II_CEPHEID_VARIABLE_CANDIDATE("Type II Cepheid Variable Candidate", "WV?"),
    GLOBULAR_CLUSTER_CANDIDATE("Globular Cluster Candidate", "Gl?"),
    LONG_PERIOD_VARIABLE_CANDIDATE("Long-Period Variable Candidate", "LP?"),
    ALPHA2_CVN_VARIABLE_CANDIDATE("alpha2 CVn Variable Candidate", "a2?"),
    MIRA_VARIABLE_CANDIDATE("Mira Variable Candidate", "Mi?"),
    T_TAURI_STAR_CANDIDATE("T Tauri Star Candidate", "TT?"),
    MOVING_GROUP("Moving Group", "MGr"),
    STARBURST_GALAXY("Starburst Galaxy", "SBG"),
    BLAZAR_CANDIDATE("Blazar Candidate", "Bz?"),
    CHEMICALLY_PECULIAR_STAR_CANDIDATE("Chemically Peculiar Star Candidate", "Pe?"),
    BL_LAC("BL Lac", "BLL"),
    ALPHA2_CVN_VARIABLE("alpha2 CVn Variable", "a2*"),
    GROUP_OF_GALAXIES_CANDIDATE("Group of Galaxies Candidate", "Gr?"),
    CARBON_STAR_CANDIDATE("Carbon Star Candidate", "C*?"),
    IRREGULAR_VARIABLE("Irregular Variable", "Ir*"),
    SEYFERT_2_GALAXY("Seyfert 2 Galaxy", "Sy2"),
    RS_CVN_VARIABLE_CANDIDATE("RS CVn Variable Candidate", "RS?"),
    EVOLVED_STAR("Evolved Star", "Ev*"),
    BLUE_OBJECT("Blue Object", "blu"),
    NEBULA("Nebula", "GNe"),
    HOT_SUBDWARF_CANDIDATE("Hot Subdwarf Candidate", "HS?"),
    INTERSTELLAR_SHELL("Interstellar Shell", "sh"),
    STAR("Star", "*"),
    BLUE_SUPERGIANT("Blue Supergiant", "s*b"),
    MASSIVE_STAR("Massive Star", "Ma*"),
    BLACK_HOLE("Black Hole", "BH"),
    LOW_MASS_X_RAY_BINARY_CANDIDATE("Low Mass X-ray Binary Candidate", "LX?"),
    NOT_AN_OBJECT_ERROR_ARTEFACT("Not an Object (Error, Artefact, ...)", "err"),
    PULSATING_VARIABLE("Pulsating Variable", "Pu*"),
    ULTRA_LUMINOUS_X_RAY_SOURCE_CANDIDATE("Ultra-luminous X-ray Source Candidate", "UX?"),
    BETA_CEP_VARIABLE("beta Cep Variable", "bC*"),
    CLASSICAL_CEPHEID_VARIABLE("Classical Cepheid Variable", "cC*"),
    HERBIG_AE_BE_STAR("Herbig Ae/Be Star", "Ae*"),
    GAMMA_RAY_BURST("Gamma-ray Burst", "gB"),
    PAIR_OF_GALAXIES("Pair of Galaxies", "PaG"),
    HIGH_MASS_X_RAY_BINARY("High Mass X-ray Binary", "HXB"),
    EXTRA_SOLAR_PLANET("Extra-solar Planet", "Pl"),
    GRAVITATIONALLY_LENSED_IMAGE_OF_A_QUASAR("Gravitationally Lensed Image of a Quasar", "LeQ"),
    OPTICAL_SOURCE("Optical Source", "Opt"),
    LOW_MASS_STAR_AND_SUBSTELLAR_OBJECTS_CANDIDATE("Low-mass Star and substellar objects Candidate", "LM?"),
    X_RAY_SOURCE("X-ray Source", "X"),
    INTERACTING_GALAXIES("Interacting Galaxies", "IG"),
    DELTA_SCT_VARIABLE("delta Sct Variable", "dS*"),
    DOUBLE_OR_MULTIPLE_STAR_CANDIDATE("Double or Multiple Star Candidate", "**?"),
    SPECTROSCOPIC_BINARY_CANDIDATE("Spectroscopic Binary Candidate", "SB?"),
    LOW_MASS_STAR("Low-mass Star", "LM*"),
    ASSOCIATION_OF_STARS_CANDIDATE("Association of Stars Candidate", "As?"),
    SUPERNOVA_REMNANT_CANDIDATE("SuperNova Remnant Candidate", "SR?"),
    GALAXY_TOWARDS_A_CLUSTER_OF_GALAXIES("Galaxy towards a Cluster of Galaxies", "GiC"),
    T_TAURI_STAR("T Tauri Star", "TT*"),
    BLUE_SUPERGIANT_CANDIDATE("Blue Supergiant Candidate", "s?b"),
    BE_STAR("Be Star", "Be*"),
    RADIO_BURST("Radio Burst", "rB"),
    OPEN_CLUSTER("Open Cluster", "OpC"),
    RR_LYRAE_VARIABLE("RR Lyrae Variable", "RR*"),
    INTERSTELLAR_FILAMENT("Interstellar Filament", "flt"),
    MIRA_VARIABLE("Mira Variable", "Mi*"),
    RADIO_GALAXY("Radio Galaxy", "rG"),
    LOW_MASS_X_RAY_BINARY("Low Mass X-ray Binary", "LXB"),
    SEYFERT_1_GALAXY("Seyfert 1 Galaxy", "Sy1"),
    RED_SUPERGIANT_CANDIDATE("Red Supergiant Candidate", "s?r"),
    RADIO_SOURCE("Radio Source", "Rad"),
    YELLOW_SUPERGIANT("Yellow Supergiant", "s*y"),
    PROTO_CLUSTER_OF_GALAXIES("Proto Cluster of Galaxies", "PCG"),
    HERBIG_AE_BE_STAR_CANDIDATE("Herbig Ae/Be Star Candidate", "Ae?"),
    SUPERCLUSTER_OF_GALAXIES("Supercluster of Galaxies", "SCG"),
    SUPERCLUSTER_OF_GALAXIES_CANDIDATE("Supercluster of Galaxies Candidate", "SC?"),
    INFRA_RED_SOURCE("Infra-Red Source", "IR"),
    GRAVITATIONALLY_LENSED_IMAGE("Gravitationally Lensed Image", "LeI"),
    BLUE_STRAGGLER("Blue Straggler", "BS*"),
    DARK_CLOUD_NEBULA("Dark Cloud (nebula)", "DNe"),
    SUPERNOVA_REMNANT("SuperNova Remnant", "SNR"),
    ELLIPSOIDAL_VARIABLE_CANDIDATE("Ellipsoidal Variable Candidate", "El?"),
    OUTFLOW("Outflow", "out"),
    SYMBIOTIC_STAR("Symbiotic Star", "Sy*"),
    BETA_CEP_VARIABLE_CANDIDATE("beta Cep Variable Candidate", "bC?"),
    HIGH_VELOCITY_STAR("High Velocity Star", "HV*"),
    CARBON_STAR("Carbon Star", "C*"),
    GRAVITATIONALLY_LENSED_IMAGE_CANDIDATE("Gravitationally Lensed Image Candidate", "LI?"),
    SUPERNOVA("SuperNova", "SN*"),
    OH_IR_STAR_CANDIDATE("OH/IR Star Candidate", "OH?"),
    SX_PHE_VARIABLE("SX Phe Variable", "SX*"),
    DENSE_CORE("Dense Core", "cor"),
    SUPERNOVA_CANDIDATE("SuperNova Candidate", "SN?"),
    R_CRB_VARIABLE("R CrB Variable", "RC*"),
    VARIABLE_STAR_CANDIDATE("Variable Star Candidate", "V*?"),
    QUASAR("Quasar", "QSO"),
    MAIN_SEQUENCE_STAR("Main Sequence Star", "MS*"),
    DOUBLE_OR_MULTIPLE_STAR("Double or Multiple Star", "**"),
    BROWN_DWARF_CANDIDATE("Brown Dwarf Candidate", "BD?"),
    ULTRA_LUMINOUS_X_RAY_SOURCE("Ultra-luminous X-ray Source", "ULX"),
    PART_OF_CLOUD("Part of Cloud", "PoC"),
    LOW_SURFACE_BRIGHTNESS_GALAXY("Low Surface Brightness Galaxy", "LSB"),
    LINER_TYPE_ACTIVE_GALAXY_NUCLEUS("LINER-type Active Galaxy Nucleus", "LIN"),
    BLUE_STRAGGLER_CANDIDATE("Blue Straggler Candidate", "BS?"),
    TYPE_II_CEPHEID_VARIABLE("Type II Cepheid Variable", "WV*"),
    OBJECT_OF_UNKNOWN_NATURE("Object of Unknown Nature", "?"),
    PLANETARY_NEBULA_CANDIDATE("Planetary Nebula Candidate", "PN?"),
    NEAR_IR_SOURCE_3_M("Near-IR Source (λ < 3 µm)", "NIR"),
    PULSATING_VARIABLE_CANDIDATE("Pulsating Variable Candidate", "Pu?"),
    CLASSICAL_NOVA("Classical Nova", "No*"),
    GALAXY("Galaxy", "G"),
    HII_REGION("HII Region", "HII"),
    HIGH_MASS_X_RAY_BINARY_CANDIDATE("High Mass X-ray Binary Candidate", "HX?"),
    PART_OF_A_GALAXY("Part of a Galaxy", "PoG"),
    HIGH_PROPER_MOTION_STAR("High Proper Motion Star", "PM*"),
    OUTFLOW_CANDIDATE("Outflow Candidate", "of?"),
    ASYMPTOTIC_GIANT_BRANCH_STAR_CANDIDATE("Asymptotic Giant Branch Star Candidate", "AB?"),
    EVOLVED_SUPERGIANT("Evolved Supergiant", "sg*"),
    CLASSICAL_NOVA_CANDIDATE("Classical Nova Candidate", "No?"),
    EXTRA_SOLAR_PLANET_CANDIDATE("Extra-solar Planet Candidate", "Pl?"),
    GAMMA_RAY_SOURCE("Gamma-ray Source", "gam"),
    LONG_PERIOD_VARIABLE("Long-Period Variable", "LP*"),
    ORION_VARIABLE("Orion Variable", "Or*"),
    MAIN_SEQUENCE_STAR_CANDIDATE("Main Sequence Star Candidate", "MS?"),
    MICRO_LENSING_EVENT("(Micro)Lensing Event", "Lev"),
    VARIABLE_STAR("Variable Star", "V*"),
    ERUPTIVE_VARIABLE_CANDIDATE("Eruptive Variable Candidate", "Er?"),
    BL_LAC_CANDIDATE("BL Lac Candidate", "BL?"),
    ECLIPSING_BINARY_CANDIDATE("Eclipsing Binary Candidate", "EB?"),
    WHITE_DWARF_CANDIDATE("White Dwarf Candidate", "WD?"),
    EMISSION_LINE_STAR("Emission-line Star", "Em*"),
    ECLIPSING_BINARY("Eclipsing Binary", "EB*"),
    GLOBULAR_CLUSTER("Globular Cluster", "GlC"),
    EVOLVED_STAR_CANDIDATE("Evolved Star Candidate", "Ev?"),
    SUB_MILLIMETRIC_SOURCE("Sub-Millimetric Source", "smm"),
    MASER("Maser", "Mas"),
    INTERSTELLAR_MEDIUM_OBJECT("Interstellar Medium Object", "ISM"),
    GRAVITATIONAL_SOURCE("Gravitational Source", "grv"),
    GRAVITATIONAL_WAVE_EVENT("Gravitational Wave Event", "GWE"),
    CHEMICALLY_PECULIAR_STAR("Chemically Peculiar Star", "Pe*"),
    ASSOCIATION_OF_STARS("Association of Stars", "As*"),
    FAR_IR_SOURCE_30_M("Far-IR source (λ >= 30 µm)", "FIR"),
    GALAXY_IN_PAIR_OF_GALAXIES("Galaxy in Pair of Galaxies", "GiP"),
    CLUSTER_OF_STARS_CANDIDATE("Cluster of Stars Candidate", "Cl?"),
    OH_IR_STAR("OH/IR Star", "OH*"),
    ROTATING_VARIABLE("Rotating Variable", "Ro*"),
    WHITE_DWARF("White Dwarf", "WD*"),
    ASYMPTOTIC_GIANT_BRANCH_STAR("Asymptotic Giant Branch Star", "AB*"),
    CLUSTER_OF_GALAXIES("Cluster of Galaxies", "ClG"),
    CENTIMETRIC_RADIO_SOURCE("Centimetric Radio Source", "cm"),
    SPECTROSCOPIC_BINARY("Spectroscopic Binary", "SB*"),
    BY_DRA_VARIABLE("BY Dra Variable", "BY*"),
    UV_EMISSION_SOURCE("UV-emission Source", "UV"),
    POST_AGB_STAR("Post-AGB Star", "pA*"),
    BLACK_HOLE_CANDIDATE("Black Hole Candidate", "BH?"),
    NEUTRON_STAR_CANDIDATE("Neutron Star Candidate", "N*?"),
    HIGH_VELOCITY_CLOUD("High-velocity Cloud", "HVC"),
    PULSAR("Pulsar", "Psr"),
    REFLECTION_NEBULA("Reflection Nebula", "RNe"),
    GROUP_OF_GALAXIES("Group of Galaxies", "GrG"),
    R_CRB_VARIABLE_CANDIDATE("R CrB Variable Candidate", "RC?"),
    RED_SUPERGIANT("Red Supergiant", "s*r"),
    GALAXY_CANDIDATE("Galaxy Candidate", "G?"),
    X_RAY_BINARY_CANDIDATE("X-ray Binary Candidate", "XB?"),
    S_STAR("S Star", "S*"),
    RS_CVN_VARIABLE("RS CVn Variable", "RS*"),
    REGION_DEFINED_IN_THE_SKY("Region defined in the Sky", "reg"),
    METRIC_RADIO_SOURCE("Metric Radio Source", "mR"),
    ROTATING_VARIABLE_CANDIDATE("Rotating Variable Candidate", "Ro?"),
    RED_GIANT_BRANCH_STAR("Red Giant Branch star", "RG*"),
    MASSIVE_STAR_OR_ITS_REMNANT_CANDIDATE("Massive Star or its Remnant Candidate", "Ma?"),
    HERBIG_HARO_OBJECT("Herbig-Haro Object", "HH"),
    HORIZONTAL_BRANCH_STAR("Horizontal Branch Star", "HB*"),
    HII_GALAXY("HII Galaxy", "H2G"),
    MILLIMETRIC_RADIO_SOURCE("Millimetric Radio Source", "mm"),
    WOLF_RAYET_CANDIDATE("Wolf-Rayet Candidate", "WR?"),
    GRAVITATIONALLY_LENSED_IMAGE_OF_A_GALAXY("Gravitationally Lensed Image of a Galaxy", "LeG"),
    COMETARY_GLOBULE_PILLAR("Cometary Globule / Pillar", "CGb"),
    CLUSTER_OF_GALAXIES_CANDIDATE("Cluster of Galaxies Candidate", "C?G"),
    YOUNG_STELLAR_OBJECT_CANDIDATE("Young Stellar Object Candidate", "Y*?"),
    ELLIPSOIDAL_VARIABLE("Ellipsoidal Variable", "El*"),
    HOT_SUBDWARF("Hot Subdwarf", "HS*"),
    EMISSION_OBJECT("Emission Object", "EmO"),
    EVOLVED_SUPERGIANT_CANDIDATE("Evolved Supergiant Candidate", "sg?"),
    GAMMA_DOR_VARIABLE("gamma Dor Variable", "gD*"),
    CEPHEID_VARIABLE_CANDIDATE("Cepheid Variable Candidate", "Ce?"),
    BE_STAR_CANDIDATE("Be Star Candidate", "Be?"),
    EMISSION_LINE_GALAXY("Emission-line galaxy", "EmG"),
    STAR_FORMING_REGION("Star Forming Region", "SFR"),
    HI_21CM_SOURCE("HI (21cm) Source", "HI"),
    YELLOW_SUPERGIANT_CANDIDATE("Yellow Supergiant Candidate", "s?y"),
    YOUNG_STELLAR_OBJECT("Young Stellar Object", "Y*O"),
    POST_AGB_STAR_CANDIDATE("Post-AGB Star Candidate", "pA?"),
    UNDERDENSE_REGION_OF_THE_UNIVERSE("Underdense Region of the Universe", "vid"),
    GRAVITATIONAL_LENS("Gravitational Lens", "gLe"),
    HORIZONTAL_BRANCH_STAR_CANDIDATE("Horizontal Branch Star Candidate", "HB?"),
    BRIGHTEST_GALAXY_IN_A_CLUSTER_BCG("Brightest Galaxy in a Cluster (BCG)", "BiC"),
    ACTIVE_GALAXY_NUCLEUS_CANDIDATE("Active Galaxy Nucleus Candidate", "AG?");

    companion object {

        @JvmStatic private val ENTRIES = values()
        @JvmStatic private val MAPPED_ENTRIES = ENTRIES.associateBy { it.code }
        @JvmStatic private val EXTRA_MAPPED_ENTRIES = mapOf(
            "C?*" to CLUSTER_OF_STARS_CANDIDATE,
        )

        @JvmStatic
        fun of(type: String) = MAPPED_ENTRIES[type] ?: EXTRA_MAPPED_ENTRIES[type]
    }
}
