name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          # cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test
        run: ./gradlew test --no-daemon --continue -Dgithub=true

      - name: Build
        run: ./gradlew :desktop:bootJar

      - name: Rename Build
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: mv desktop/build/libs/desktop.jar desktop-linux.jar

      - name: Rename Build
        if: ${{ matrix.os == 'windows-latest' }}
        run: mv desktop/build/libs/desktop.jar desktop-windows.jar

      - name: Deploy
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          overwrite: true
          update_latest_release: true
          verbose: true
          file: 'desktop-*.jar'
