name: Deploy

on:
  workflow_dispatch:

jobs:
  api:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew --no-daemon :api:shadowJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-${{ github.sha }}
          path: desktop/api.jar
          retention-days: 1

  desktop:
    needs: api
    name: Build Desktop App
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: desktop

    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2025, ubuntu-22.04-arm ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download API
        uses: actions/download-artifact@v4
        with:
          name: api-${{ github.sha }}
          path: desktop

      - name: Install Dependencies
        run: npm i

      - name: Install Linux x64 Build Dependencies
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: sudo apt install -y rpm libarchive-tools

      - name: Install Linux arm64 Build Dependencies
        if: ${{ matrix.os == 'ubuntu-22.04-arm' }}
        run: sudo apt install -y libarchive-tools ruby ruby-dev && sudo gem install fpm

      - name: Build Linux x64 & Windows
        if: ${{ matrix.os != 'ubuntu-22.04-arm' }}
        run: npm run electron:build

      - name: Build Linux arm64
        if: ${{ matrix.os == 'ubuntu-22.04-arm' }}
        run: USE_SYSTEM_FPM=true npm run electron:build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nebulosa-${{ matrix.os }}-${{ github.sha }}
          path: |
            desktop/release/nebulosa*.AppImage
            desktop/release/nebulosa*.deb
            desktop/release/nebulosa*.rpm
            desktop/release/nebulosa*.pacman
            desktop/release/nebulosa*.exe
            desktop/release/nebulosa*.msi
            desktop/release/nebulosa*.dmg
          retention-days: 1
